.test:cargo:
  stage: test
  script:
    - cargo fmt --all -- --check
    - cargo clippy --all --tests --all-features
    - cargo test --all
    - cargo test --all --release
    - cargo test --all --release --features inspect-release

stages:
  - test

.stable:test:
  extends: .test:cargo
  image: rustdocker/rust:stable

.beta:test:
  extends: .test:cargo
  image: rustdocker/rust:beta

nightly:test:
  extends: .test:cargo
  image: rustdocker/rust:nightly
